steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/portfolio-frontend', '--build-arg', 'NEXT_PUBLIC_API_URL=${_BACKEND_URL}', '.']
    
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/portfolio-frontend']
    
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'portfolio-frontend'
    - '--image'
    - 'gcr.io/$PROJECT_ID/portfolio-frontend'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--memory'
    - '2Gi'
    - '--cpu'
    - '1'
    - '--min-instances'
    - '0'
    - '--max-instances'
    - '10'
    - '--set-env-vars'
    - 'NEXT_PUBLIC_API_URL=${_BACKEND_URL}'

# Set a longer timeout for the build
timeout: '3600s'

# Specify the images to be pushed to Container Registry
images:
  - 'gcr.io/$PROJECT_ID/portfolio-frontend'

# Define substitution variables with defaults
substitutions:
  _BACKEND_URL: '${_BACKEND_URL}'